name: tgworker-sync

on: push

jobs:
  ronin-sync:
    runs-on: ubuntu-latest  # Use a suitable runner for your workflow
    steps:

    - uses: actions/checkout@v3

    - name: Sync with upstream
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
      with:
        target_sync_branch: main
        upstream_sync_repo: little2/tgworker
        upstream_sync_branch: main
